local myGlobal = require("__nco-LongWarehouses__/lib/nco_data")
myGlobal.imageInfo = myGlobal.imageInfo or {}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-h-bg-left.png"]={width=391, height=215}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-h-bg-mid.png"]={width=897, height=215}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-h-bg-right.png"]={width=391, height=215}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-h-bg.png"]={width=1676, height=215}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-h-building.png"]={width=202, height=80}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-v-bg-left.png"]={width=268, height=391}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-v-bg-mid.png"]={width=268, height=897}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-v-bg-right.png"]={width=268, height=391}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-v-bg.png"]={width=268, height=1677}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/warehouse-v-building.png"]={width=64, height=213}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/hr/addon-power-pole-shadow.png"]={width=128, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/hr/addon-power-pole.png"]={width=74, height=151}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/hr/warehouse-h-building.png"]={width=951, height=340}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/entity/hr/warehouse-v-building.png"]={width=256, height=852}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/addon-power-pole.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/error.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/tech-warehouses-logistics.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/tech-warehouses.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-active-provider.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-buffer.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-normal.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-passive-provider.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-requester.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/warehouse-storage.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_A.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_B.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_C.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_D.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_E.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_F.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_G.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_H.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_I.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_J.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_K.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_L.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_M.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_N.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_O.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_P.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_Q.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_R.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_S.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_T.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_U.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_V.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_W.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_X.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_Y.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Letters/icon_Z.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_0.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_1.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_10.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_100.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_101.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_102.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_103.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_104.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_105.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_106.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_107.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_108.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_109.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_11.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_110.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_111.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_112.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_113.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_114.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_115.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_116.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_117.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_118.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_119.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_12.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_120.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_121.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_122.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_123.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_124.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_125.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_126.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_127.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_128.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_129.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_13.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_130.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_131.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_132.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_133.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_134.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_135.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_136.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_137.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_138.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_139.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_14.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_140.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_141.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_142.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_143.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_144.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_145.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_146.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_147.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_148.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_149.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_15.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_150.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_151.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_152.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_153.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_154.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_155.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_156.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_157.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_158.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_159.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_16.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_160.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_161.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_162.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_163.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_164.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_165.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_166.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_167.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_168.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_169.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_17.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_170.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_171.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_172.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_173.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_174.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_175.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_176.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_177.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_178.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_179.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_18.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_180.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_181.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_182.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_183.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_184.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_185.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_186.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_187.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_188.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_189.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_19.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_190.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_191.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_192.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_193.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_194.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_195.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_196.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_197.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_198.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_199.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_2.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_20.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_200.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_201.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_202.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_203.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_204.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_205.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_206.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_207.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_208.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_209.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_21.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_210.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_211.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_212.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_213.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_214.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_215.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_216.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_217.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_218.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_219.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_22.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_220.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_221.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_222.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_223.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_224.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_225.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_226.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_227.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_228.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_229.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_23.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_230.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_231.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_232.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_233.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_234.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_235.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_236.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_237.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_238.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_239.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_24.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_240.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_241.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_242.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_243.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_244.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_245.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_246.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_247.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_248.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_249.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_25.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_250.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_251.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_252.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_253.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_254.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_255.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_26.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_27.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_28.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_29.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_3.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_30.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_31.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_32.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_33.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_34.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_35.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_36.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_37.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_38.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_39.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_4.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_40.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_41.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_42.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_43.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_44.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_45.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_46.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_47.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_48.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_49.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_5.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_50.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_51.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_52.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_53.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_54.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_55.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_56.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_57.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_58.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_59.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_6.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_60.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_61.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_62.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_63.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_64.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_65.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_66.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_67.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_68.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_69.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_7.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_70.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_71.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_72.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_73.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_74.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_75.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_76.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_77.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_78.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_79.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_8.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_80.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_81.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_82.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_83.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_84.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_85.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_86.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_87.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_88.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_89.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_9.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_90.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_91.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_92.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_93.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_94.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_95.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_96.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_97.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_98.png"]={width=64, height=64}
myGlobal.imageInfo["__nco-LongWarehouses__/graphics/icons/Numbers/icon_99.png"]={width=64, height=64}
